//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RealEstateEntities : DbContext
    {
        public RealEstateEntities()
            : base("name=RealEstateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<agent> agents { get; set; }
        public virtual DbSet<apartment> apartments { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<deal> deals { get; set; }
        public virtual DbSet<demand> demands { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<house> houses { get; set; }
        public virtual DbSet<human> humen { get; set; }
        public virtual DbSet<land> lands { get; set; }
        public virtual DbSet<land_demand> land_demand { get; set; }
        public virtual DbSet<live_demand> live_demand { get; set; }
        public virtual DbSet<supply> supplies { get; set; }
        public virtual DbSet<type_demand> type_demand { get; set; }
    }
}
