//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate
{
    using System;
    using System.Collections.Generic;
    
    public partial class deal
    {
        public int Id { get; set; }
        public Nullable<int> DemandId { get; set; }
        public Nullable<int> SupplyId { get; set; }
    
        public virtual demand demand { get; set; }
    }
}
